-- Prestige orchestrator foundation (trusted compute/write pipe).
-- This migration intentionally avoids hard-coded prestige economy rules.

create table if not exists public.prestige_state_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  emitter text not null,
  user_id uuid null references public.profiles (id) on delete set null,
  outcome text not null
    constraint prestige_state_audit_outcome_check check (
      outcome in ('updated', 'unchanged', 'error')
    ),
  details jsonb not null default '{}'::jsonb
);

comment on table public.prestige_state_audit is
  'Trusted audit log for prestige/frame orchestrator outcomes.';

create index if not exists prestige_state_audit_user_idx
  on public.prestige_state_audit (user_id, created_at desc);

alter table public.prestige_state_audit enable row level security;

revoke all on table public.prestige_state_audit from public;
revoke all on table public.prestige_state_audit from anon;
revoke all on table public.prestige_state_audit from authenticated;

create or replace function public.orchestrate_prestige_profile_frame(
  p_user_id uuid,
  p_current_tier text,
  p_frame_name text,
  p_motif_family text,
  p_accent_tier text,
  p_source_basis jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tier text;
  v_name text;
  v_motif text;
  v_accent text;
  v_basis jsonb;
  v_existing public.prestige_profile_frames%rowtype;
  v_saved public.prestige_profile_frames%rowtype;
  v_changed boolean := false;
begin
  if p_user_id is null then
    raise exception 'user_id is required';
  end if;

  v_tier := trim(coalesce(p_current_tier, ''));
  v_name := trim(coalesce(p_frame_name, ''));
  v_motif := trim(coalesce(p_motif_family, ''));
  v_accent := trim(coalesce(p_accent_tier, ''));

  if v_tier = '' then raise exception 'current_tier is required'; end if;
  if v_name = '' then raise exception 'frame_name is required'; end if;
  if v_motif = '' then raise exception 'motif_family is required'; end if;
  if v_accent = '' then raise exception 'accent_tier is required'; end if;

  v_basis := coalesce(p_source_basis, '[]'::jsonb);
  if jsonb_typeof(v_basis) is distinct from 'array' and jsonb_typeof(v_basis) is distinct from 'object' then
    raise exception 'source_basis must be a json object or array';
  end if;

  select *
    into v_existing
  from public.prestige_profile_frames
  where user_id = p_user_id
  limit 1;

  if found then
    v_changed :=
      v_existing.current_tier is distinct from v_tier
      or v_existing.frame_name is distinct from v_name
      or v_existing.motif_family is distinct from v_motif
      or v_existing.accent_tier is distinct from v_accent
      or v_existing.source_basis is distinct from v_basis;

    update public.prestige_profile_frames
    set
      current_tier = v_tier,
      frame_name = v_name,
      motif_family = v_motif,
      accent_tier = v_accent,
      source_basis = v_basis,
      updated_at = case when v_changed then now() else v_existing.updated_at end
    where user_id = p_user_id
    returning * into v_saved;
  else
    insert into public.prestige_profile_frames (
      user_id,
      current_tier,
      frame_name,
      motif_family,
      accent_tier,
      source_basis,
      updated_at
    )
    values (
      p_user_id,
      v_tier,
      v_name,
      v_motif,
      v_accent,
      v_basis,
      now()
    )
    returning * into v_saved;
    v_changed := true;
  end if;

  insert into public.prestige_state_audit (emitter, user_id, outcome, details)
  values (
    'orchestrate_prestige_profile_frame',
    p_user_id,
    case when v_changed then 'updated' else 'unchanged' end,
    jsonb_build_object(
      'frame_id', v_saved.id,
      'current_tier', v_saved.current_tier,
      'frame_name', v_saved.frame_name,
      'motif_family', v_saved.motif_family,
      'accent_tier', v_saved.accent_tier,
      'updated_at', v_saved.updated_at
    )
  );

  return jsonb_build_object(
    'updated', v_changed,
    'reason', case when v_changed then 'updated' else 'unchanged' end,
    'frame_id', v_saved.id,
    'user_id', v_saved.user_id,
    'current_tier', v_saved.current_tier,
    'frame_name', v_saved.frame_name,
    'motif_family', v_saved.motif_family,
    'accent_tier', v_saved.accent_tier,
    'updated_at', v_saved.updated_at
  );
exception
  when others then
    insert into public.prestige_state_audit (emitter, user_id, outcome, details)
    values (
      'orchestrate_prestige_profile_frame',
      p_user_id,
      'error',
      jsonb_build_object('error', sqlerrm)
    );
    raise;
end;
$$;

comment on function public.orchestrate_prestige_profile_frame(
  uuid, text, text, text, text, jsonb
) is
  'Trusted prestige compute/write orchestrator. Idempotent update semantics; stores current frame state and audit outcomes.';

-- Compute contract (deferred callers):
-- - Caller computes frame fields from system truth inputs:
--   * six-bucket ratings
--   * trophy records
--   * vault relic records
--   * tournament accomplishments
-- - Caller passes normalized frame state + source_basis snapshot to this function.

revoke all on function public.orchestrate_prestige_profile_frame(
  uuid, text, text, text, text, jsonb
) from public;

grant execute on function public.orchestrate_prestige_profile_frame(
  uuid, text, text, text, text, jsonb
) to service_role;
