-- Vault milestone emitter (first trusted caller).
-- Narrow milestone only: finished game winner relic issuance.
-- This migration does not implement broad reward policy.

create table if not exists public.vault_relic_issuance_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  emitter text not null,
  user_id uuid null references public.profiles (id) on delete set null,
  milestone_key text null,
  source_game_id uuid null references public.games (id) on delete set null,
  source_tournament_id uuid null references public.tournaments (id) on delete set null,
  outcome text not null
    constraint vault_relic_issuance_audit_outcome_check check (
      outcome in ('issued', 'already_issued', 'skipped', 'error')
    ),
  details jsonb not null default '{}'::jsonb
);

comment on table public.vault_relic_issuance_audit is
  'Trusted audit trail for Vault relic issuance attempts and outcomes.';

create index if not exists vault_relic_issuance_audit_game_idx
  on public.vault_relic_issuance_audit (source_game_id, created_at desc);

create index if not exists vault_relic_issuance_audit_user_idx
  on public.vault_relic_issuance_audit (user_id, created_at desc);

alter table public.vault_relic_issuance_audit enable row level security;

-- Players should not read or write issuance audit logs directly.
revoke all on table public.vault_relic_issuance_audit from public;
revoke all on table public.vault_relic_issuance_audit from anon;
revoke all on table public.vault_relic_issuance_audit from authenticated;

create or replace function public.emit_vault_relic_for_finished_game_winner(
  p_game_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  g public.games%rowtype;
  v_user_id uuid;
  v_category text;
  v_pace text;
  v_milestone_key text;
  v_title text;
  v_description text;
  v_outcome jsonb;
begin
  if p_game_id is null then
    raise exception 'game_id is required';
  end if;

  select *
    into g
  from public.games
  where id = p_game_id;

  if not found then
    raise exception 'game not found';
  end if;

  if g.status is distinct from 'finished' then
    insert into public.vault_relic_issuance_audit (
      emitter,
      source_game_id,
      source_tournament_id,
      outcome,
      details
    )
    values (
      'emit_vault_relic_for_finished_game_winner',
      p_game_id,
      g.tournament_id,
      'skipped',
      jsonb_build_object('reason', 'not_finished')
    );
    return jsonb_build_object('issued', false, 'reason', 'not_finished');
  end if;

  v_user_id := g.winner_id;
  if v_user_id is null then
    if g.result = 'white_win' then
      v_user_id := g.white_player_id;
    elsif g.result = 'black_win' then
      v_user_id := g.black_player_id;
    end if;
  end if;

  if v_user_id is null then
    insert into public.vault_relic_issuance_audit (
      emitter,
      source_game_id,
      source_tournament_id,
      outcome,
      details
    )
    values (
      'emit_vault_relic_for_finished_game_winner',
      p_game_id,
      g.tournament_id,
      'skipped',
      jsonb_build_object('reason', 'no_winner')
    );
    return jsonb_build_object('issued', false, 'reason', 'no_winner');
  end if;

  v_category :=
    case
      when lower(trim(coalesce(g.play_context, 'free'))) = 'tournament' then 'tournament'
      else 'free'
    end;

  v_pace :=
    case
      when lower(trim(coalesce(g.tempo, ''))) in ('live', 'daily', 'correspondence')
        then lower(trim(g.tempo))
      else null
    end;

  v_milestone_key := format('game_finish:%s:winner', g.id::text);
  v_title := 'Game Winner';
  v_description := 'Awarded for winning a finished game.';

  v_outcome := public.orchestrate_vault_relic_issuance(
    p_user_id => v_user_id,
    p_milestone_key => v_milestone_key,
    p_title => v_title,
    p_category => v_category,
    p_date_won => coalesce(g.finished_at, now()),
    p_source_game_id => g.id,
    p_source_tournament_id => g.tournament_id,
    p_pace => v_pace,
    p_description => v_description
  );

  insert into public.vault_relic_issuance_audit (
    emitter,
    user_id,
    milestone_key,
    source_game_id,
    source_tournament_id,
    outcome,
    details
  )
  values (
    'emit_vault_relic_for_finished_game_winner',
    v_user_id,
    v_milestone_key,
    g.id,
    g.tournament_id,
    case
      when coalesce((v_outcome->>'issued')::boolean, false) then 'issued'
      when coalesce(v_outcome->>'reason', '') = 'already_issued' then 'already_issued'
      else 'skipped'
    end,
    v_outcome
  );

  return v_outcome;
exception
  when others then
    insert into public.vault_relic_issuance_audit (
      emitter,
      source_game_id,
      outcome,
      details
    )
    values (
      'emit_vault_relic_for_finished_game_winner',
      p_game_id,
      'error',
      jsonb_build_object('error', sqlerrm)
    );
    raise;
end;
$$;

comment on function public.emit_vault_relic_for_finished_game_winner(uuid) is
  'Trusted milestone emitter for finished-game winner relic. Computes canonical key game_finish:<game_id>:winner and calls orchestrate_vault_relic_issuance.';

revoke all on function public.emit_vault_relic_for_finished_game_winner(uuid) from public;
grant execute on function public.emit_vault_relic_for_finished_game_winner(uuid) to service_role;
