-- Trophy issuance foundation (trusted + idempotent).
-- This migration does NOT define award rules; it only provides secure issuance plumbing.

alter table public.trophy_records
  add column if not exists milestone_key text null;

alter table public.trophy_records
  drop constraint if exists trophy_records_milestone_key_not_blank;

alter table public.trophy_records
  add constraint trophy_records_milestone_key_not_blank check (
    milestone_key is null or btrim(milestone_key) <> ''
  );

comment on column public.trophy_records.milestone_key is
  'Idempotency key from trusted trophy milestone orchestrator.';

create unique index if not exists trophy_records_user_milestone_key_uidx
  on public.trophy_records (user_id, milestone_key)
  where milestone_key is not null;

create table if not exists public.trophy_issuance_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  emitter text not null,
  user_id uuid null references public.profiles (id) on delete set null,
  milestone_key text null,
  source_game_id uuid null references public.games (id) on delete set null,
  source_tournament_id uuid null references public.tournaments (id) on delete set null,
  outcome text not null
    constraint trophy_issuance_audit_outcome_check check (
      outcome in ('issued', 'already_issued', 'skipped', 'error')
    ),
  details jsonb not null default '{}'::jsonb
);

comment on table public.trophy_issuance_audit is
  'Trusted audit trail for trophy issuance outcomes.';

create index if not exists trophy_issuance_audit_user_idx
  on public.trophy_issuance_audit (user_id, created_at desc);

create index if not exists trophy_issuance_audit_milestone_idx
  on public.trophy_issuance_audit (milestone_key, created_at desc);

alter table public.trophy_issuance_audit enable row level security;

revoke all on table public.trophy_issuance_audit from public;
revoke all on table public.trophy_issuance_audit from anon;
revoke all on table public.trophy_issuance_audit from authenticated;

create or replace function public.issue_trophy_record(
  p_user_id uuid,
  p_title text,
  p_category text,
  p_date_awarded timestamptz default null,
  p_source_game_id uuid default null,
  p_source_tournament_id uuid default null,
  p_placement integer default null,
  p_level text default null,
  p_description text default null
)
returns public.trophy_records
language plpgsql
security definer
set search_path = public
as $$
declare
  v_title text;
  v_category text;
  v_level text;
  v_desc text;
  v_row public.trophy_records%rowtype;
begin
  if p_user_id is null then
    raise exception 'user_id is required';
  end if;

  v_title := trim(coalesce(p_title, ''));
  if v_title = '' then
    raise exception 'title is required';
  end if;

  v_category := trim(coalesce(p_category, ''));
  if v_category = '' then
    raise exception 'category is required';
  end if;

  if p_placement is not null and p_placement <= 0 then
    raise exception 'placement must be positive when provided';
  end if;

  v_level := nullif(trim(coalesce(p_level, '')), '');
  v_desc := nullif(trim(coalesce(p_description, '')), '');

  insert into public.trophy_records (
    user_id,
    title,
    category,
    date_awarded,
    source_game_id,
    source_tournament_id,
    placement,
    level,
    description
  )
  values (
    p_user_id,
    v_title,
    v_category,
    p_date_awarded,
    p_source_game_id,
    p_source_tournament_id,
    p_placement,
    v_level,
    v_desc
  )
  returning * into v_row;

  return v_row;
end;
$$;

comment on function public.issue_trophy_record(
  uuid, text, text, timestamptz, uuid, uuid, integer, text, text
) is
  'Trusted trophy issuance RPC. For server-side milestone handlers only.';

revoke all on function public.issue_trophy_record(
  uuid, text, text, timestamptz, uuid, uuid, integer, text, text
) from public;
grant execute on function public.issue_trophy_record(
  uuid, text, text, timestamptz, uuid, uuid, integer, text, text
) to service_role;

create or replace function public.orchestrate_trophy_issuance(
  p_user_id uuid,
  p_milestone_key text,
  p_title text,
  p_category text,
  p_date_awarded timestamptz default null,
  p_source_game_id uuid default null,
  p_source_tournament_id uuid default null,
  p_placement integer default null,
  p_level text default null,
  p_description text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text;
  v_existing public.trophy_records%rowtype;
  v_created public.trophy_records%rowtype;
begin
  if p_user_id is null then
    raise exception 'user_id is required';
  end if;

  v_key := lower(trim(coalesce(p_milestone_key, '')));
  if v_key = '' then
    raise exception 'milestone_key is required';
  end if;

  select *
    into v_existing
  from public.trophy_records
  where user_id = p_user_id
    and milestone_key = v_key
  limit 1;

  if found then
    insert into public.trophy_issuance_audit (
      emitter, user_id, milestone_key, source_game_id, source_tournament_id, outcome, details
    )
    values (
      'orchestrate_trophy_issuance',
      p_user_id,
      v_key,
      p_source_game_id,
      p_source_tournament_id,
      'already_issued',
      jsonb_build_object('trophy_id', v_existing.id, 'reason', 'already_issued')
    );

    return jsonb_build_object(
      'issued', false,
      'reason', 'already_issued',
      'trophy_id', v_existing.id,
      'milestone_key', v_existing.milestone_key
    );
  end if;

  select *
    into v_created
  from public.issue_trophy_record(
    p_user_id,
    p_title,
    p_category,
    p_date_awarded,
    p_source_game_id,
    p_source_tournament_id,
    p_placement,
    p_level,
    p_description
  );

  begin
    update public.trophy_records
    set milestone_key = v_key
    where id = v_created.id
    returning * into v_created;
  exception
    when unique_violation then
      select *
        into v_existing
      from public.trophy_records
      where user_id = p_user_id
        and milestone_key = v_key
      limit 1;

      insert into public.trophy_issuance_audit (
        emitter, user_id, milestone_key, source_game_id, source_tournament_id, outcome, details
      )
      values (
        'orchestrate_trophy_issuance',
        p_user_id,
        v_key,
        p_source_game_id,
        p_source_tournament_id,
        'already_issued',
        jsonb_build_object('trophy_id', v_existing.id, 'reason', 'already_issued_concurrent')
      );

      return jsonb_build_object(
        'issued', false,
        'reason', 'already_issued',
        'trophy_id', v_existing.id,
        'milestone_key', v_existing.milestone_key
      );
  end;

  insert into public.trophy_issuance_audit (
    emitter, user_id, milestone_key, source_game_id, source_tournament_id, outcome, details
  )
  values (
    'orchestrate_trophy_issuance',
    p_user_id,
    v_key,
    p_source_game_id,
    p_source_tournament_id,
    'issued',
    jsonb_build_object('trophy_id', v_created.id, 'reason', 'ok')
  );

  return jsonb_build_object(
    'issued', true,
    'reason', 'ok',
    'trophy_id', v_created.id,
    'milestone_key', v_created.milestone_key
  );
exception
  when others then
    insert into public.trophy_issuance_audit (
      emitter, user_id, milestone_key, source_game_id, source_tournament_id, outcome, details
    )
    values (
      'orchestrate_trophy_issuance',
      p_user_id,
      v_key,
      p_source_game_id,
      p_source_tournament_id,
      'error',
      jsonb_build_object('error', sqlerrm)
    );
    raise;
end;
$$;

comment on function public.orchestrate_trophy_issuance(
  uuid, text, text, text, timestamptz, uuid, uuid, integer, text, text
) is
  'Trusted trophy milestone orchestrator. Idempotent by (user_id, milestone_key); calls issue_trophy_record internally.';

-- Milestone event contract (deferred callers):
-- {
--   user_id: uuid,
--   milestone_key: text,  -- stable deterministic idempotency key
--   title: text,
--   category: text,
--   date_awarded?: timestamptz,
--   source_game_id?: uuid|null,
--   source_tournament_id?: uuid|null,
--   placement?: integer|null,
--   level?: text|null,
--   description?: text|null
-- }

revoke all on function public.orchestrate_trophy_issuance(
  uuid, text, text, text, timestamptz, uuid, uuid, integer, text, text
) from public;
grant execute on function public.orchestrate_trophy_issuance(
  uuid, text, text, text, timestamptz, uuid, uuid, integer, text, text
) to service_role;
